# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a34bd40ff2a53e796f1a0a85dbb64b32"
name = "Flow app 2024"
handle = "flow-app-2024"
application_url = "https://arena-app-tt.ap.ngrok.io"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "tamaki-co-shop.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://arena-app-tt.ap.ngrok.io/auth/callback" ]

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[app_proxy]
url = "https://arena-app-tt.ap.ngrok.io/proxy"
subpath = "store-pickup"
prefix = "apps"

[pos]
embedded = false

[app_preferences]
url = "https://arena-app-tt.ap.ngrok.io/preferences"
